# Generated by Django 5.0.3 on 2024-04-04 07:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_parameter_remove_course_category_delete_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='inlet',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
