# Generated by Django 5.0.3 on 2024-04-04 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_parameter_stage_1_pressure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameter',
            name='inlet',
        ),
        migrations.AddField(
            model_name='parameter',
            name='Stage_1_1_temp',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='parameter',
            name='Stage_1_2_temp',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='parameter',
            name='Stage_2_1_temp',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='parameter',
            name='Stage_2_2_temp',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='parameter',
            name='comp_current',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='parameter',
            name='comp_oil_temp',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='parameter',
            name='compressure_oil',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='parameter',
            name='discharge',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='parameter',
            name='gas_detector',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parameter',
            name='inlet_puressure',
            field=models.FloatField(default=0.0),
        ),
    ]
