# Generated by Django 5.0.3 on 2024-04-04 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_compressure_oil_parameter_compressure_oil_pressure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameter',
            name='inlet_puressure',
        ),
        migrations.AddField(
            model_name='parameter',
            name='inletPressure',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='hour_meter',
            field=models.FloatField(default=0.0),
        ),
    ]
