# Generated by Django 5.0.3 on 2024-04-04 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_inletpressure_parameter_inlet_puressure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameter',
            name='Stage_1_1_temp',
        ),
        migrations.RemoveField(
            model_name='parameter',
            name='Stage_1_2_temp',
        ),
        migrations.RemoveField(
            model_name='parameter',
            name='Stage_2_1_temp',
        ),
        migrations.RemoveField(
            model_name='parameter',
            name='Stage_2_2_temp',
        ),
        migrations.RemoveField(
            model_name='parameter',
            name='comp_current',
        ),
        migrations.RemoveField(
            model_name='parameter',
            name='comp_oil_temp',
        ),
        migrations.RemoveField(
            model_name='parameter',
            name='compressure_oil_pressure',
        ),
        migrations.RemoveField(
            model_name='parameter',
            name='discharge',
        ),
        migrations.RemoveField(
            model_name='parameter',
            name='gas_detector',
        ),
    ]
