# Generated by Django 5.0.3 on 2024-04-04 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_inlet_puressure_parameter_inlet_pressure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='stage_1_pressure',
            field=models.FloatField(default=0.0),
        ),
    ]
