# Generated by Django 5.0.3 on 2024-04-04 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_parameter_stage_1_pressure'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='discharge_pressure',
            field=models.FloatField(default=0.0),
        ),
    ]
