# Generated by Django 5.0.3 on 2024-04-05 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_parameter_discharge_pressure'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='comp_oil_temp',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='parameter',
            name='compressor_oil_presure',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='parameter',
            name='gas_detector',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='parameter',
            name='motor_current',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='parameter',
            name='st_1_1_temp',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='parameter',
            name='st_1_2_temp',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='parameter',
            name='st_2_1_temp',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='parameter',
            name='st_2_2_temp',
            field=models.FloatField(default=0.0),
        ),
    ]
